import java.awt.Color;
import javax.swing.JPanel;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vishalnirmal
 */
public class t extends javax.swing.JFrame {

    /**
     * Creates new form t
     */
    public t() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 113, 113));

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 113, 113));

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3MouseEntered(evt);
            }
        });
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 113, 113));

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
        });
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 113, 113));

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5MouseEntered(evt);
            }
        });
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 113, 113));

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b6MouseEntered(evt);
            }
        });
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 113, 113));

        b7.setBackground(new java.awt.Color(255, 255, 255));
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b7MouseEntered(evt);
            }
        });
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 113, 113));

        b8.setBackground(new java.awt.Color(255, 255, 255));
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 113, 113));

        b9.setBackground(new java.awt.Color(255, 255, 255));
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 113, 113));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WIN_20170201_07_59_54_Pro.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int n=1;
char ar[]={'1','2','3','4','5','6','7','8','9'};
ImageIcon i1 = new ImageIcon("C:\\Users\\vishalnirmal\\Documents\\NetBeansProjects\\Vishal\\X.jpg");
ImageIcon i2 = new ImageIcon("C:\\Users\\vishalnirmal\\Documents\\NetBeansProjects\\Vishal\\O.jpg");
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(n%2==0&&ar[0]=='1')
        {
            b1.setIcon(i2);
            ar[0]='X';
            n++;
        }
        else if(n%2==1&&ar[0]=='1')
        {
            b1.setIcon(i1);
            ar[0]='O';
            n++;
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        
    }//GEN-LAST:event_b1MouseClicked

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(n%2==0&&ar[1]=='2')
        {
            b2.setIcon(i2);
            ar[1]='X';
            n++;
        }
        else if(n%2==1&&ar[1]=='2')
        {
            b2.setIcon(i1);
            ar[1]='O';
            n++;
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(n%2==0&&ar[2]=='3')
        {
            b3.setIcon(i2);
            ar[2]='X';
            n++;
        }
        else if(n%2==1&&ar[2]=='3')
        {
            b3.setIcon(i1);
            ar[2]='O';
            n++;
        }
        
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
           b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(n%2==0&&ar[3]=='4')
        {
            b4.setIcon(i2);
            ar[3]='X';
            n++;
        }
        else if(n%2==1&&ar[3]=='4')
        {
            b4.setIcon(i1);
            ar[3]='O';
            n++;
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
            ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(n%2==0&&ar[4]=='5')
        {
            b5.setIcon(i2);
            ar[4]='X';
            n++;
        }
        else if(n%2==1&&ar[4]=='5')
        {
            b5.setIcon(i1);
            ar[4]='O';
            n++;
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       if(n%2==0&&ar[5]=='6')
        {
            b6.setIcon(i2);
            ar[5]='X';
            n++;
        }
        else if(n%2==1&&ar[5]=='6')
        {
            b6.setIcon(i1);
            ar[5]='O';
            n++;
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(n%2==0&&ar[6]=='7')
        {
            b7.setIcon(i2);
            ar[6]='X';
            n++;
        }
        else if(n%2==1&&ar[6]=='7')
        {
            b7.setIcon(i1);
            ar[6]='O';
            n++;
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(n%2==0&&ar[7]=='8')
        {
            b8.setIcon(i2);
            ar[7]='X';
            n++;
        }
        else if(n%2==1&&ar[7]=='8')
        {
            b8.setIcon(i1);
            ar[7]='O';
            n++;
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(n%2==0&&ar[8]=='9')
        {
            b9.setIcon(i2);
            ar[8]='X';
            n++;
        }
        else if(n%2==1&&ar[8]=='9')
        {
            b9.setIcon(i1);
            ar[8]='O';
            n++;
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Already taken!");
        
        if((ar[0]==ar[1]&&ar[1]==ar[2])||(ar[3]==ar[4]&&ar[4]==ar[5])||(ar[6]==ar[7]&&ar[7]==ar[8])||(ar[0]==ar[3]&&ar[3]==ar[6])||(ar[1]==ar[4]&&ar[4]==ar[7])||(ar[2]==ar[5]&&ar[5]==ar[8])||(ar[0]==ar[4]&&ar[4]==ar[8])||(ar[2]==ar[4]&&ar[4]==ar[6]))
        {
            if(n%2==0)
                 JOptionPane.showMessageDialog(rootPane, "Player 1 Wins!!");
             else
                 JOptionPane.showMessageDialog(rootPane, "Player 2 Wins!!");
            n=1;
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
        if(n==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Draw");
            for(int i=0;i<9;i++)
                ar[i]=(char)(i+48+1);
            b1.setIcon(null);
            b2.setIcon(null);
            b3.setIcon(null);
            b4.setIcon(null);
            b5.setIcon(null);
            b6.setIcon(null);
            b7.setIcon(null);
            b8.setIcon(null);
            b9.setIcon(null);
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        b1.setBackground(Color.white);
    }//GEN-LAST:event_b1MouseEntered

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
        b2.setBackground(Color.white);
    }//GEN-LAST:event_b2MouseEntered

    private void b3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseEntered
        b3.setBackground(Color.white);
    }//GEN-LAST:event_b3MouseEntered

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
        b4.setBackground(Color.white);
    }//GEN-LAST:event_b4MouseEntered

    private void b5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseEntered
        b5.setBackground(Color.white);
    }//GEN-LAST:event_b5MouseEntered

    private void b6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseEntered
        b6.setBackground(Color.white);
    }//GEN-LAST:event_b6MouseEntered

    private void b7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseEntered
        b7.setBackground(Color.white);
    }//GEN-LAST:event_b7MouseEntered
    private void b8MouseEntered(java.awt.event.MouseEvent evt) {
        b8.setBackground(Color.white);
    }
    private void b9MouseEntered(java.awt.event.MouseEvent evt) {
        b9.setBackground(Color.white);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(t.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(t.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(t.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(t.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new t().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
